"""
Example network automation script showing PPPoE subscriber provisioning
on MikroTik RouterOS v7 via the REST API.

This script represents a simplified component of a zero-touch provisioning
workflow where new customer installations trigger automated account creation
through an orchestration pipeline.
"""

import requests
import logging
import os
import sys

# Configure Logging for Audit Trails
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# Environment Variables for Security
MIKROTIK_IP = os.getenv("MIKROTIK_IP", "10.255.0.1")
API_USER = os.getenv("API_USER", "api_provisioner")
# Fallback provided for local assessment testing
API_PASS = os.getenv("API_PASS", "AssessmentFallbackPass123!")

BASE_URL = f"https://{MIKROTIK_IP}/rest/ppp/secret"

VALID_SERVICE_TIERS = [
    "10Mbps_Residential",
    "20Mbps_Residential",
    "50Mbps_SME"
]

# Fail-fast validation
if not API_PASS:
    raise ValueError("API_PASS environment variable is not set.")

# Establish a reusable session for connection pooling
session = requests.Session()
session.auth = (API_USER, API_PASS)
session.headers.update({"Content-Type": "application/json"})


def provision_pppoe_subscriber(username, password, service_tier):
    """
    Provision a PPPoE subscriber on MikroTik RouterOS v7 via the REST API.

    Parameters:
        username (str): Subscriber PPPoE username
        password (str): Authentication password
        service_tier (str): RouterOS PPP profile applied for bandwidth control
    """

    # Basic username validation
    if " " in username:
        logging.error("Username contains invalid whitespace.")
        return False

    # Validate service tier
    if service_tier not in VALID_SERVICE_TIERS:
        logging.error(f"Invalid service tier: {service_tier}")
        return False

    payload = {
        "name": username,
        "password": password,
        "service": "pppoe",
        "profile": service_tier,
        "comment": "Auto-Provisioned via Network Automation Pipeline"
    }

    try:
        logging.info(
            f"[Router {MIKROTIK_IP}] Provisioning PPPoE subscriber '{username}' | Profile: {service_tier}"
        )

        # Retry logic for transient API failures
        for attempt in range(3):
            try:
                response = session.post(
                    BASE_URL,
                    json=payload,
                    verify=True,  # RouterOS TLS certificate validated against system CA
                    timeout=10
                )
                break
            except requests.exceptions.RequestException:
                if attempt == 2:
                    raise
                logging.warning("API request failed, retrying...")

        if response.status_code in [200, 201]:
            logging.info(f"SUCCESS: Subscriber {username} successfully provisioned.")
            return True

        try:
            error_detail = response.json()
        except ValueError:
            error_detail = response.text

        logging.error(f"FAILED: RouterOS API returned {response.status_code} - {error_detail}")
        return False

    except requests.exceptions.RequestException as e:
        logging.critical(f"CRITICAL: Failed to reach MikroTik API. Error: {e}")
        return False


if __name__ == "__main__":
    # Example trigger (simulating UISP webhook provisioning event)
    pipeline_success = provision_pppoe_subscriber(
        username="sunway_house_402",
        password="AutoGeneratedAuthKey",
        service_tier="20Mbps_Residential"
    )

    # Communicate execution status back to the CI/CD runner
    sys.exit(0 if pipeline_success else 1)
